"""Problema 4: Una videoteca digital necesita identificar rápidamente qué 
material audiovisual es popular y reciente. La información está en una 
matriz: [Título, Año de Lanzamiento, Calificación (1-10), Género]. 
"""
#Requisitos de Desarrollo 
""" 
- Matriz: Crear una matriz con al menos 7 títulos. 
- Módulos: Se requiere un módulo (función) para contar la 
cantidad de títulos que satisfacen un conjunto de criterios. 
"""  
#- Lógica de Negocio: 
"""✓ Contar los títulos que tienen una Calificación mayor o igual 
     a un umbral dado Y cuyo Año de Lanzamiento es 
    posterior o igual a un año límite establecido. """
#- Salida: Mostrar el conteo total de títulos que cumplen con ambos criterios. 
# vamos a agregar bastantes, que paresca un analisis complejo de analisis de datos real
matrix = [
    ["The Godfather", 1972, 10, "Crimen"],
    ["Parasite", 2019, 9, "Drama"],
    ["Spirited Away", 2001, 9, "Animación"],
    ["City of God", 2002, 9, "Crimen"],
    ["Amélie", 2001, 8, "Romance"],
    ["Seven Samurai", 1954, 10, "Acción"],
    ["Pan's Labyrinth", 2006, 9, "Fantasía"],
    ["Life is Beautiful", 1997, 9, "Drama"],
    ["Inception", 2010, 9, "Ciencia Ficción"],
    ["Oldboy", 2003, 9, "Thriller"],
    ["Roma", 2018, 8, "Drama"],
    ["Crouching Tiger, Hidden Dragon", 2000, 8, "Acción"],
    ["The Dark Knight", 2008, 10, "Acción"],
    ["Interstellar", 2014, 9, "Ciencia Ficción"],
    ["The Lives of Others", 2006, 9, "Drama"],
    ["Slumdog Millionaire", 2008, 8, "Drama"],
    ["Your Name", 2016, 9, "Animación"],
    ["The Intouchables", 2011, 9, "Comedia"],
    ["Shrek", 2001, 8, "Animación"],
    ["The Matrix", 1999, 10, "Ciencia Ficción"],
    ["Pulp Fiction", 1994, 10, "Crimen"],
    ["Fight Club", 1999, 9, "Drama"],
    ["Forrest Gump", 1994, 9, "Drama"],
    ["The Shawshank Redemption", 1994, 10, "Drama"],
    ["Gladiator", 2000, 9, "Acción"],
    ["Titanic", 1997, 9, "Romance"],
    ["The Silence of the Lambs", 1991, 9, "Thriller"],
    ["Schindler's List", 1993, 10, "Drama"],
    ["Goodfellas", 1990, 9, "Crimen"],
    ["The Pianist", 2002, 9, "Drama"],
    ["La La Land", 2016, 8, "Musical"],
    ["Joker", 2019, 9, "Drama"],
    ["Avengers: Endgame", 2019, 8, "Acción"],
    ["Black Panther", 2018, 8, "Acción"],
    ["The Lion King", 1994, 9, "Animación"],
    ["Toy Story", 1995, 9, "Animación"],
    ["Coco", 2017, 9, "Animación"],
    ["Frozen", 2013, 8, "Animación"],
    ["The Prestige", 2006, 9, "Thriller"],
    ["Memento", 2000, 9, "Thriller"],
    ["Blade Runner", 1982, 9, "Ciencia Ficción"],
    ["Blade Runner 2049", 2017, 9, "Ciencia Ficción"],
    ["Arrival", 2016, 9, "Ciencia Ficción"],
    ["Gravity", 2013, 8, "Ciencia Ficción"],
    ["The Revenant", 2015, 8, "Drama"],
    ["Birdman", 2014, 9, "Drama"],
    ["The Grand Budapest Hotel", 2014, 8, "Comedia"],
    ["Moonlight", 2016, 8, "Drama"],
    ["Her", 2013, 9, "Romance"],
    ["Whiplash", 2014, 9, "Drama"],
    ["Mad Max: Fury Road", 2015, 9, "Acción"],
    ["The Irishman", 2019, 8, "Crimen"],
    ["Django Unchained", 2012, 9, "Crimen"],
    ["Inglourious Basterds", 2009, 9, "Acción"],
    ["Kill Bill: Vol. 1", 2003, 9, "Acción"],
    ["Kill Bill: Vol. 2", 2004, 9, "Acción"],
    ["The Hateful Eight", 2015, 8, "Western"],
    ["Once Upon a Time in Hollywood", 2019, 8, "Drama"],
    ["The Wolf of Wall Street", 2013, 9, "Comedia"],
    ["Catch Me If You Can", 2002, 8, "Drama"],
    ["The Social Network", 2010, 9, "Drama"],
    ["The Truman Show", 1998, 9, "Drama"],
    ["Eternal Sunshine of the Spotless Mind", 2004, 9, "Romance"],
    ["The Green Mile", 1999, 9, "Drama"],
    ["American Beauty", 1999, 9, "Drama"],
    ["The Sixth Sense", 1999, 9, "Thriller"],
    ["A Beautiful Mind", 2001, 9, "Drama"],
    ["Cast Away", 2000, 8, "Drama"],
    ["The Departed", 2006, 9, "Crimen"],
    ["The Aviator", 2004, 8, "Drama"],
    ["Everything Everywhere All at Once", 2022, 9, "Ciencia Ficción"],
    ["RRR", 2022, 9, "Acción"],
    ["Drive My Car", 2021, 9, "Drama"],
    ["The Power of the Dog", 2021, 8, "Drama"],
    ["Dune", 2021, 9, "Ciencia Ficción"],
    ["Top Gun: Maverick", 2022, 9, "Acción"],
    ["The Whale", 2022, 8, "Drama"],
    ["Barbie", 2023, 8, "Comedia"],
    ["Oppenheimer", 2023, 10, "Drama"],
    ["Poor Things", 2023, 9, "Fantasía"],
    ["The Zone of Interest", 2023, 9, "Drama"],
    ["Past Lives", 2023, 9, "Romance"],
    ["Anatomy of a Fall", 2023, 9, "Thriller"],
    ["The Holdovers", 2023, 8, "Comedia"],
    ["Spider-Man: Across the Spider-Verse", 2023, 10, "Animación"],
    ["The Batman", 2022, 9, "Acción"],
    ["Nope", 2022, 8, "Terror"],
    ["The Menu", 2022, 8, "Thriller"],
    ["Triangle of Sadness", 2022, 8, "Comedia"],
    ["Aftersun", 2022, 9, "Drama"],
    ["Argentina, 1985", 2022, 9, "Drama"],
    ["All Quiet on the Western Front", 2022, 9, "Guerra"],
    ["Decision to Leave", 2022, 9, "Thriller"],
    ["The Worst Person in the World", 2021, 9, "Romance"],
    ["CODA", 2021, 9, "Drama"],
    ["Minari", 2020, 9, "Drama"],
    ["Soul", 2020, 9, "Animación"],
    ["Nomadland", 2020, 9, "Drama"],
    ["Sound of Metal", 2019, 9, "Drama"],
    ["1917", 2019, 9, "Guerra"],
    ["Parasite", 2019, 10, "Drama"],
    ["Jojo Rabbit", 2019, 9, "Comedia"],
    ["Marriage Story", 2019, 9, "Drama"],
    ["Knives Out", 2019, 9, "Thriller"],
    ["The Farewell", 2019, 9, "Drama"],
    ["Shoplifters", 2018, 9, "Drama"],
    ["Roma", 2018, 9, "Drama"],
    ["Cold War", 2018, 9, "Romance"],
    ["Burning", 2018, 9, "Drama"],
    ["A Fantastic Woman", 2017, 9, "Drama"],
    ["The Square", 2017, 8, "Comedia"],
    ["Call Me by Your Name", 2017, 9, "Romance"],
    ["The Shape of Water", 2017, 9, "Fantasía"],
    ["Lady Bird", 2017, 9, "Drama"],
    ["Moonlight", 2016, 9, "Drama"],
    ["Your Name", 2016, 9, "Animación"],
    ["The Handmaiden", 2016, 9, "Thriller"],
    ["Hacksaw Ridge", 2016, 9, "Guerra"],
    ["The Salesman", 2016, 9, "Drama"],
    ["Spotlight", 2015, 9, "Drama"],
    ["Room", 2015, 9, "Drama"],
    ["Brooklyn", 2015, 8, "Romance"],
    ["Son of Saul", 2015, 9, "Drama"],
    ["Inside Out", 2015, 9, "Animación"],
    ["Boyhood", 2014, 9, "Drama"],
    ["Ida", 2013, 9, "Drama"],
    ["Blue Is the Warmest Color", 2013, 9, "Romance"],
    ["The Hunt", 2012, 9, "Drama"],
    ["Amour", 2012, 9, "Drama"],
    ["A Separation", 2011, 10, "Drama"],
    ["Incendies", 2010, 9, "Drama"],
    ["The Secret in Their Eyes", 2009, 9, "Crimen"],
    ["Let the Right One In", 2008, 9, "Terror"],
    ["Pan's Labyrinth", 2006, 9, "Fantasía"],
    ["El secreto de sus ojos", 2009, 9, "Crimen"],        
    ["Relatos salvajes", 2014, 9, "Comedia"],             
    ["Nueve reinas", 2000, 8, "Crimen"],                  
    ["Ciudad de Dios", 2002, 10, "Crimen"],            
    ["Central do Brasil", 1998, 9, "Drama"],           
    ["Tropa de Elite", 2007, 9, "Acción"],             
    ["Y tu mamá también", 2001, 9, "Drama"],           
    ["Amores perros", 2000, 9, "Drama"],               
    ["Roma", 2018, 9, "Drama"],                              
    ["La jaula de oro", 2013, 8, "Drama"],                
    ["La estrategia del caracol", 1993, 9, "Drama"],     
    ["Los colores de la montaña", 2010, 8, "Drama"],     
    ["Monos", 2019, 9, "Drama"],                         
    ["La vendedora de rosas", 1998, 9, "Drama"],         
    ["Whisky", 2004, 8, "Comedia"],                     
    ["Machuca", 2004, 9, "Drama"],                    
    ["Una mujer fantástica", 2017, 9, "Drama"],          
    ["El abrazo de la serpiente", 2015, 9, "Aventura"],   
    ["Cinema Paradiso", 1988, 10, "Drama"],               
    ["La dolce vita", 1960, 9, "Drama"],                  
    ["La grande bellezza", 2013, 9, "Drama"],             
    ["Das Leben der Anderen", 2006, 9, "Drama"],          
    ["Toni Erdmann", 2016, 9, "Comedia"],                 
    ["Good Bye Lenin!", 2003, 9, "Comedia"],              
    ["Intouchables", 2011, 9, "Comedia"],                
    ["Amélie", 2001, 9, "Romance"], 
    ["Batman & Robin", 1997, 4, "Acción"],
    ["Catwoman", 2004, 4, "Acción"],
    ["The Room", 2003, 4, "Drama"],
    ["Movie 43", 2013, 4, "Comedia"],
    ["Gigli", 2003, 4, "Romance"],
    ["Dragonball Evolution", 2009, 4, "Ciencia Ficción"],
    ["Superbabies: Baby Geniuses 2", 2004, 3, "Comedia"],
    ["Jaws: The Revenge", 1987, 4, "Terror"],
    ["Battlefield Earth", 2000, 4, "Ciencia Ficción"],
    ["Son of the Mask", 2005, 4, "Comedia"],                     
    ["La haine", 1995, 9, "Drama"],                      
    ["The Square", 2017, 8, "Comedia"],                   
    ["Fanny och Alexander", 1982, 9, "Drama"],            
    ["Dogtooth", 2009, 9, "Drama"],                       
    ["The Lobster", 2015, 8, "Comedia"],                  
    ["The Man Without a Past", 2002, 8, "Drama"],         
    ["The Killing of a Sacred Deer", 2017, 8, "Thriller"],
    ["Rashomon", 1950, 10, "Drama"],                     
    ["Ikiru", 1952, 10, "Drama"],                        
    ["Departures", 2008, 9, "Drama"],                    
    ["Shoplifters", 2018, 9, "Drama"],                   
    ["Drive My Car", 2021, 9, "Drama"],                  
    ["Parasite", 2019, 10, "Drama"],                      
    ["Oldboy", 2003, 9, "Thriller"],                      
    ["Memories of Murder", 2003, 9, "Crimen"],            
    ["Burning", 2018, 9, "Drama"],                        
    ["Decision to Leave", 2022, 9, "Thriller"],           
    ["Lagaan", 2001, 9, "Drama"],                 
    ["RRR", 2022, 9, "Acción"],                   
    ["Pather Panchali", 1955, 10, "Drama"],               
    ["Gully Boy", 2019, 8, "Drama"],                      
    ["The Lunchbox", 2013, 9, "Romance"],                 
    ["Infernal Affairs", 2002, 9, "Crimen"],              
    ["In the Mood for Love", 2000, 10, "Romance"],       
    ["Chungking Express", 1994, 9, "Drama"],             
    ["Tsotsi", 2005, 8, "Drama"],                        
    ["Yesterday", 2004, 8, "Drama"],                     
    ["Mandela: Long Walk to Freedom", 2013, 8, "Biografía"], 
    ["Cairo Station", 1958, 9, "Drama"],                  
    ["Yomeddine", 2018, 8, "Drama"],                      
    ["Atlantics", 2019, 8, "Drama"],                      
    ["Timbuktu", 2014, 9, "Drama"],                       
    ["Hyenas", 1992, 8, "Drama"],                         
    ["The Night of Counting the Years", 1969, 9, "Drama"],
    ["Sankofa", 1993, 8, "Drama"],
    ["El Paseo 2", 2012, 5, "Comedia"],          
    ["La mujer de mi hermano", 2005, 5, "Drama"],
    ["Cásese quien pueda", 2014, 5, "Comedia"],  
    ["No se aceptan devoluciones", 2013, 6, "Comedia"], 
    ["Señorita María: la falda de la montaña", 2017, 6, "Documental"],
    ["Suicide Squad", 2016, 6, "Acción"],
    ["Venom", 2018, 6, "Acción"],
    ["Transformers: Age of Extinction", 2014, 6, "Acción"],
    ["The Da Vinci Code", 2006, 7, "Thriller"],
    ["Twilight", 2008, 6, "Romance"],
    ["The Meg", 2018, 6, "Acción"],
    ["Pacific Rim: Uprising", 2018, 6, "Ciencia Ficción"],
    ["The Amazing Spider-Man 2", 2014, 6, "Acción"],
    ["Justice League", 2017, 6, "Acción"],
    ["Thor: The Dark World", 2013, 6, "Acción"],
    ["Attack on Titan (live action)", 2015, 6, "Acción"], 
    ["Death Note (Netflix)", 2017, 5, "Thriller"],        
    ["The Great Yokai War", 2005, 6, "Fantasía"],    
    ["RoboGeisha", 2009, 6, "Acción"],               
    ["Gully Boy", 2019, 7, "Drama"],                 
    ["Kabir Singh", 2019, 6, "Romance"],             
    ["Dilwale", 2015, 6, "Romance"],                 
    ["Shaolin Soccer", 2001, 7, "Comedia"],              
    ["Kung Fu Hustle", 2004, 7, "Comedia"],              
    ["Ip Man 4", 2019, 7, "Acción"],                        
]
#evaluamos valores
año_minimo = int(input("coloque aqui el año minimo de preferencia"))
año_maximo = int(input("coloque aqui el año maximo de preferencia"))
calificacion_minima = int(input("coloque aqui su calificacion de preferencia"))
print("M"*35)
generos = [
    "Acción","Drama",
    "Crimen","Thriller",
    "Romance","Comedia",
    "Animación","Ciencia Ficción",
    "Fantasía","Musical",
    "Western","Guerra",
    "Biografía","Documental",
    "Aventura","Terror"
]
# imprimimos cada género:
for i, genero in enumerate(generos, start=1):
   print(f"{i}. {genero}")
#preguntamos cual es el genero:    
genero_de_preferencia = (input("coloque aqui su genero de preferencia:")).lower()
#abrimos un bucle para evaluar las variables:(generamos variable especifica;concatenar)
"""abrimos otra matriz para la variables"""
peliculas_concatenadas = [
    p for p in matrix
    if  p[3].lower() == genero_de_preferencia
    and año_minimo <= p[1] <= año_maximo
    and p[2] >= calificacion_minima 

]
#SALIDA:::::
print(f"="*70)
print(f"_"*70)
print(f"\nPeliculas del genero:{genero_de_preferencia.capitalize()},entre los rangos {año_minimo}, y {año_maximo}")
for i,p in enumerate(peliculas_concatenadas, start=1):
    print(f"{i},[{p[0]}],([{p[1]}]),{p[2]}")
print(f"="*70)
print(f"Los titulos son: {len(peliculas_concatenadas)}")
print("\n" + "="*70)
